# Generated by Django 4.2.3 on 2023-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('idEmpleado', models.CharField(max_length=5, unique=True)),
                ('salarioBase', models.CharField(max_length=20)),
                ('horasTrabajadas', models.CharField(max_length=5)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
